import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'

import './globals.css'
import { cn } from '@/lib/utils'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          geistSans.variable,
          geistMono.variable,
          'bg-neutral-900 text-neutral-50 antialiased'
        )}
      >
        <header className="sticky top-0 z-10 text-sm h-[60px] font-semibold border-b border-neutral-800">
          <div className="px-5 h-full mx-auto">
            <div className="flex justify-between items-center h-full">
              <div>
                <Link
                  className="font-bold text-pink-500 hover:text-pink-400"
                  href="/"
                >
                  ESIX
                </Link>
              </div>
              <nav
                aria-label="Main navigation"
                className="text-neutral-400"
              >
                <ul className="flex items-center gap-4 list-none">
                  <li className="block">
                    <Link
                      className="px-3 py-[19px] font-bold hover:text-white"
                      href="/docs"
                    >
                      Docs
                    </Link>
                  </li>

                  <li className="block">
                    <Link
                      className="px-3 py-[19px] font-bold hover:text-white"
                      href="/api"
                    >
                      API
                    </Link>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </header>

        <main>{children}</main>

        <footer className="py-10 text-sm font-medium text-neutral-400 border-t border-neutral-800"></footer>
      </body>
    </html>
  )
}
